### ISSUE TITLE
Adblocker filters bootstrap-social

### ISSUE THREAD

**Issue by pzv-** [lipis/bootstrap-social#50] opened 2014-11-20 14:22 UTC
Just for info:
unfourtunately, Adblock filters bootstrap-social:
https://easylist-downloads.adblockplus.org/fanboy-social.txt

Is there a way to prevent this?

Best, Thomas

**Comment by lipis** [comment] 2014-11-20 20:17
Hmmm... that's a tricky one.. cause in a way it belongs to category social :) you could get it and rename it.. but eventually if become popular it will be blocked again.. not much we can do I guess

**Comment by gameguy43** [comment] 2015-05-19 21:29
FWIW, I've gotten several emails from users who were confused and frustrated that they couldn't log in to my site. It took some digging to learn this was the issue.

I've tested locally and confirmed that simply changing the class name to something other than btn-facebook prevents the blocking. Something like btn-soc-facebook successfully bypasses the block, and seems reasonable in the scope of this project (adds a layer of namespacing, which might be a good thing anyway).

The /intent/ of fanboy-social, as I understand, is to block the fancy embedded share buttons that track you as you move around the web, /even when you don't click them/. I say that based on this post:
https://adblockplus.org/blog/about-that-facebook-tracking-thing

So I think making this adjustment is /not/ just playing a game of cat and mouse. I don't think the author(s) of fanboy-social would feel it necessary to adjust their list to block bootstrap-social buttons--I think they were blocked unintentionally. Therefore I claim this classname change would be purely a bugfix.

I understand project maintainers might disagree with this claim though, and a class name change kinda breaks backwards compatibility. But if project maintainers agree with me, I'm happy to write a PR. Let me know.

**Comment by gameguy43** [comment] 2015-05-19 21:56
Spoke too soon...the fix I'm proposing almost works, but the fontawesome icons still get blocked.

The fact this filter blocks fa- classes is ... ugh. Perhaps they /do/ intend to block /all/ buttons /in any way related/ to social. I know /my/ users who have installed this are disappointed with the behavior though. At least some of them. Ugh.

Considering merging fa into my codebase and also tweaking their classnames...That probably isn't really a viable solution for this library as a whole though. So now I'm thinking this bug is a WONTFIX :/

**Comment by gameguy43** [comment] 2015-05-19 22:08
Relevant thread on the fontawesome project:
https://github.com/FortAwesome/Font-Awesome/issues/1799

**Comment by lipis** [comment] 2015-05-20 04:14
@gameguy43 Thanks for the research, the follow up and the links.. Of course the icons are not part of this lib, but nevertheless I believe even if we're going to change the prefix they will do something else to block them, as they are blocking all the social stuff.. even when it's actually needed and not intended to spam or annoy people.. I'm not sure if there is any way to bring that subject to AdBlocker or something, as these buttons started and intended to be used as sign in buttons..

**Comment by ghstahl** [comment] 2015-07-22 04:20
what we need is to have a post process to personalize the entire stack to me.   This would obfuscate all names to my organization, hence never get noticed as popular usage.  i.e. I believe Bootstrap has some sort customization on their site to make a custom bootstrap just for me, minus the obfuscation.

**Comment by lipis** [comment] 2016-09-06 22:49
I think I'll just close this one.. not much we can do.. right?

**Closed as completed by lipis** 2016-09-06 22:49 UTC

**Comment by gameguy43** [comment] 2016-09-15 16:24
FWIW: a bit of movement on this recently. Fingers crossed!

https://github.com/FortAwesome/Font-Awesome/issues/1799
https://issues.adblockplus.org/ticket/4434

**Comment by ryanbr** [comment] 2016-09-19 23:33
From: ​https://lipis.github.io/bootstrap-social/

```

  <a class="btn btn-social-icon btn-twitter">
    <span class="fa fa-twitter"></span>
  </a>

  <a class="btn btn-block btn-social btn-twitter">
    <span class="fa fa-twitter"></span> Sign in with Twitter
  </a>
```

Might be happier if they removed the class social suggestion's of using the

```
btn-twitter
btn-facebook
btn-[....]
btn-social-icon
```

Then we can simply remove the fa-[elements] from the social list.

**Comment by hellboy81** [comment] 2017-03-14 11:01
Hi, I have still problem with  `btn` `btn-facebook` classes:

```html
<div class="btn-group-justified" role="group">
<div class="btn-group" role="group">        
<!--- This element is hidden -->
<a class="btn btn-facebook" href="">
   <span class="fa fa-facebook"></span> Facebook
</a>
<!--- This element is NOT hidden -->
<a class="btn btn-google" href="">
   <span class="fa fa-google-plus"></span> Google +</a>
</div>
</div>
```
